### ISSUE TITLE
Test automatic Dependabot automerge

### ISSUE THREAD

**Issue by ponent** [ponent/xaloc#139]
Add new yaml:

```
name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.mytoken }}
```
